---
permalink: identify-deprecated-apis.html
sidebar: sidebar
keywords: learn, digital advisor, active-iq, api, query, graphql, api, rest, call
summary: "The Digital Advisor GraphQL API has limitations in place to protect against excessive or abusive calls to Digital Advisor's servers"
---
= Identify deprecated Digital Advisor REST APIs
:icons: font
:imagesdir: ./media/

[.lead]
Digital Advisor is transitioning from REST APIs to GraphQL as its primary API platform to improve performance, flexibility, and scalability. Learn how you can identify deprecated Digital Advisor REST APIs.

The transition from REST APIs to GraphQL APIs will be phased, with a period of overlap between REST APIs and GraphQL APIs. For each deprecated REST API endpoint, a deprecation notice will be published in the Digital Advisor API catalog, you need to migrate that specific endpoint to GraphQL within six months. 

CAUTION: NetApp strongly recommends that all new API integrations utilize GraphQL-based APIs.

.Steps

. Navigate to link:https://activeiq.netapp.com[Digital Advisor (ActiveIQ)^] and sign in using your NetApp Support Site credentials.

. In the top navigation bar, select *Quick Links*, and then select *API Services*.

. To review the list of APIs scheduled for deprecation, select *Browse* under the *API Catalog* icon, and then select *Deprecated APIs*.



