---
permalink: migrate-to-graphql.html
sidebar: sidebar
keywords: learn, digital advisor, active-iq, api, query, graphql, api, rest, call
summary: "The Digital Advisor GraphQL API has limitations in place to protect against excessive or abusive calls to Digital Advisor's servers"
---
= Migrate deprecated Digital Advisor REST API endpoints to GraphQL
:icons: font
:imagesdir: ./media/

[.lead]
The transition from REST APIs to GraphQL APIs will be phased, with a period of overlap between REST APIs and GraphQL APIs. Learn how to identify and migrate deprecated REST API endpoints to GraphQL.

A deprecation notice will be published in the Digital Advisor API catalog for each deprecated REST API endpoint. You need to migrate that specific endpoint to GraphQL within six months. 

CAUTION: NetApp strongly recommends that all new API integrations utilize GraphQL-based APIs.

.About this task 

* You should first focus on migrating the endpoints that already have the six month deprecation notice before you migrate other endpoints. NetApp updates these first and provides confirmed GraphQL replacements.
* GraphQL is organized around objects, not endpoints, which improves predictability. To understand the schema types, refer to the link:https://studio.apollographql.com/public/ActiveIQ-Graph-Prd-API/variant/current/explorer[GraphQL Apollo Studio explorer^].

.Steps

. Review the Digital Advisor REST APIs that you are currently using in your integration.

. Navigate to link:https://activeiq.netapp.com[Digital Advisor (ActiveIQ)^] and sign in using your NetApp Support Site credentials.

. In the top navigation bar, select *Quick Links*, and then select *API Services*.

. To review the list of APIs scheduled for deprecation, select *Browse* under the *API Catalog* icon, and then select *Deprecated APIs*.

. From the list of deprecated APIs, confirm the following:
* Whether an endpoint you are using in your integration is listed.
* The expected retirement date for endpoints you are using.

. Review the *Migration information* section which includes the equivalent GraphQL query that corresponds to each deprecated REST API endpoint.
+
NOTE: Most of the REST API endpoints have a direct functional replacement available in GraphQL. Review each deprecated REST API endpoint to find the corresponding migration information.

