jekyll: adavis-syntax-highlighter
settings:
  name: Digital Advisor API 
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    lipi_enabled: false
    harmony_enabled: false
sidebar:
  entries:
  - title: Digital Advisor API docs
    url: /index.html
  - title: Get started
    entries: 
    - title: Learn about Digital Advisor GraphQL APIs
      url: /learn-about.html
    - title: Queries and mutations
      url: /queries-mutations.html
    - title: Pagination
      url: /pagination.html
    - title: Rate and query limits
      url: /rate-query-limits.html
    - title: Error handling
      url: /error-handling.html

  - title: Use the Digital Advisor GraphQL API
    entries: 
    - title: Generate access and refresh tokens
      url: /authentication.html
    - title: Create a request
      url: /create-request.html
    - title: Use example GraphQL queries
      url: /sample-api-queries.html
  - title: Migrate from REST to GraphQL
    entries:
    - title: Learn about migrating REST to GraphQL
      url: /learn-about-migration.html
    - title: Migrate REST API endpoints to GraphQL
      url: /migrate-to-graphql.html
    - title: Update deprecated REST API calls
      url: /identify-deprecated-apis.html
  - title: Legal notices
    url: /legal-notices.html
  
  

