jekyll: adavis-syntax-highlighter
settings:
  name: Digital Advisor API 
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    lipi_enabled: false
    harmony_enabled: false
sidebar:
  entries:
  - title: Digital Advisor API docs
    url: /index.html
  - title: Get started
    entries: 
    - title: Learn about Digital Advisor GraphQL APIs
      url: /learn-about.html
    - title: GraphQL queries and mutations
      url: /queries-mutations.html
    - title: GraphQL pagination
      url: /pagination.html
    - title: GraphQL rate and query limits
      url: /rate-query-limits.html
    - title: GraphQL error handling
      url: /error-handling.html

  - title: Use the Digital Advisor GraphQL API
    entries: 
    - title: Generate access and refresh tokens
      url: /authentication.html
    - title: Create a request
      url: /create-request.html
    - title: Use example GraphQL queries
      url: /sample-api-queries.html
  - title: Migrate from REST API to GraphQL
    entries:
    - title: Migrate deprecated Digital Advisor REST API endpoints
      url: /identify-deprecated-apis.html
  - title: Legal notices
    url: /legal-notices.html
  
  

