settings:
  name: Digital Advisor API 
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    lipi_enabled: false
    harmony_enabled: false
sidebar:
  entries:
  - title: Digital Advisor API docs
    url: /index.html
  - title: Get started
    entries: 
    - title: Learn about Digital Advisor APIs
      url: /learn-about.html
    - title: Queries and mutations
      url: /queries-mutations.html
    - title: Pagination
      url: /pagination.html
    - title: Rate and query limits
      url: /rate-query-limits.html
    - title: Error handling
      url: /error-handling.html

  - title: Use the Digital Advisor GraphQL API
    entries: 
    - title: Generate tokens
      entries:
      - title: Choose the token type
        url: /decide-token-type.html
      - title: Generate a personal access token
        url: /generate-pat-token.html
      - title: Generate an access and refresh token
        url: /authentication.html
    - title: Create a request
      url: /create-request.html
    - title: Use example GraphQL queries
      url: /sample-api-queries.html
  - title: Digital Advisor MCP server
    entries: 
    - title: Learn about the Digital Advisor MCP server
      url: /learn-digital-advisor-mcp.html
    - title: Get started with the Digital Advisor MCP server
      url: /get-started-digital-advisor-mcp.html

  - title: Migrate from REST to GraphQL
    entries:
    - title: Learn about migrating REST to GraphQL
      url: /learn-about-migration.html
    - title: Migrate REST API endpoints to GraphQL
      url: /migrate-to-graphql.html
  - title: Legal notices
    url: /legal-notices.html
  
  

