---
permalink: rate-query-limits.html
sidebar: sidebar
keywords: learn, digital advisor, active-iq, api, query, graphql, api, rest, call
summary: "The Digital Advisor GraphQL API has limitations in place to protect against excessive or malicious calls to Digital Advisor's servers"
---
= Rate and query limits in Digital Advisor GraphQL APIs
:icons: font
:imagesdir: ./media/

[.lead]
The Digital Advisor GraphQL API has limitations in place to protect against excessive or malicious calls to Digital Advisor's servers.

== Request rate limit

The GraphQL API assigns points to each query and limits the requests that you can use within a specific amount of time. This limit helps prevent abuse and denial-of-service attacks, and ensures that the API remains available for all users.

There is a limit of 300 requests in any five minute period for each originating IP address. If this limit is exceeded, a client will receive the "Too Many Requests" error based on the 429 status code as shown below.

[source,json]
----
{
  "errors": [
    {
      "extensions": {
        "service": "ActiveIQ_GraphQL",
        "code": "USER_API_RATE_LIMIT_EXCEEDED",
        "status": 429
      },
      "message": "User API Rate Limit Exceeded."
    }
  ]
}
----

== Timeouts

If GraphQL API takes more than 60 seconds to process an API request, the server terminates the request and you receive a timeout response and a message reporting that that the request has timed out.