---
permalink: update-rest-api-calls.html
sidebar: sidebar
keywords: learn, digital advisor, active-iq, api, query, graphql, api, rest, call
summary: "The Digital Advisor GraphQL API has limitations in place to protect against excessive or abusive calls to Digital Advisor's servers"
---
= Update deprecated Digital Advisor REST API calls to GraphQL
:icons: font
:imagesdir: ./media/

[.lead]
You need to understand the elements of the GraphQL API in order to update your deprecated REST API calls to GraphQL. 

CAUTION: NetApp strongly recommends that all new API integrations utilize GraphQL-based APIs.

== Learn how to replace REST API calls with GraphQL

To replace the REST API calls with GraphQL, you need to learn how to do the following:

* Use queries instead of endpoints.
+
GraphQL retrieves exactly the fields you need instead of fixed REST payloads (reducing over and under fetching). For more information, see link:queries-mutations.html[Digital Advisor GraphQL API data queries and mutations].

* Pass variables instead of URL parameters.
+
GraphQL uses variables instead of URL parameters. For information on how to use variables in a query, see link:queries-mutations.html#use-variables-in-a-query[Use variables in a query].

* Consolidate multiple REST API calls.
+
With GraphQL, you can combine several requests into a single query and get all the data you need at once.
+
NOTE: Digital Advisor GraphQL APIs use the same authentication methods as the REST API for token generation. For more information, see link:authentication.html[Generate your Digital Advisor API access and refresh tokens]. 


== Test out the GraphQL API

You can use the link:https://gql.aiq.netapp.com/[GraphQL API Explorer tool^] to perform the following actions:

* Run sample queries
* Validate output
* Adjust your field selection
* Test variables
+
For more information, see link:create-request.html[Use the Digital Advisor GraphQL APIs].

After you've learned how to use the GraphQL API and validated the GraphQL version of your deprecated endpoint, update your automation code and scripts and discontinue the use of the deprecated REST call before its retirement date.

